### ISSUE TITLE
Why embedded-hal so old?

### ISSUE THREAD

**Issue by crabdancing** [onkoe/max6675_hal#1]
Firstly, good job writing a SPI driver for this hardware. I had a question though: why is your embedded-hal so old? Is it recommended to not use the newer version? Are programs using the newer version interoperable with drivers using the older version, or do they have to downgrade / driver has to be updated?

**Comment by onkoe** [comment]
Hey there! It seems that `embedded-hal` is still at stable version `1.0`. 

Could you please double-check that you're using the newest version of this crate, `max6675-hal = "1.0"`, within your workspace? 

Please reach out if you continue to face any difficulties! :)

**Comment by crabdancing** [comment]
ah! My apologies. I was looking at `main` branch, but your newest is `hal-1.0`. My bad. :P

Thanks for pointing that out!
